[build]
  command = "CI='' npm run build"
  publish = ".next"

[[plugins]]
  package = "netlify-plugin-cypress"

[[plugins]]
package = 'netlify-plugin-prisma-provider'
  [plugins.inputs]
  path = 'prisma/schema.prisma'
  varName = 'mysql'  
